apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: kf0405/hello-app:d332e7b92c722a8bae081a7bd93bdf4c50bd2c33
        ports:
        - containerPort: 80
